services:
  - type: web
    name: impostor-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TURSO_DATABASE_URL
        value: libsql://impostor-antonithecodeprogrammer.aws-eu-west-1.turso.io
      - key: TURSO_AUTH_TOKEN
        sync: false          # wpisz ręcznie w panelu Render.com
      - key: ADMIN_SEED_SECRET
        value: impostor-secret
